sudo: false
language: ruby
os:
- linux
- osx
cache:
  bundler: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
env:
  global:
  - NO_LINK_RUTIE=1
  - RUST_BACKTRACE=full
  - PATH=$PATH:$HOME/.cargo/bin
  - secure: UCarEfq9wDpD6FV0dIdfDMCWfeLoKBAM2PS+xZ82K1uoFBMtwet/UuEuz06OnX6B9k2TwV0aqQpkUuo6o+h9YoHKAGz1/O5iB5uJaHcoII8yL43LH4YUADqupsgbvFzUCdcLuKCvDVG5RD96tt5XX87UdyZMgHvBV41wKOoUF+0ZyIWq8sKFPlItM+oYN55gY+PZ5ZadsOOkWDbTAG/LuxDi1GJxb/ObiYkjk4b93xzKEx1t7H2LSs8/f8dg0w1gnM6bVXQHjdXGuAw8jqy6IoszFh2oKDyttix4yB5l5xxj/NwO/aJNmOLBRNf611WskH6RLKWteCxwyY0gIZnDlC7q+SMYJtDapuffvqqKdlC5ECcVNimw9D3DwuxizP/5IGoC5+X+RIJiWBx/RJgFV2dw22/XvC62rOMttQL1K1dUByMRJL1pjLoauofbTdJgZgdrb1eDxGNyxL+Rg8za2wqs5NtENnXY6RIX4NvSXUPE9vRLdYnmGtH5hLF36hRh5AwvgOZ544xYT2ss6FxUJNo/zphlE7zfZrD+waeUBRUabzi6S5xEBXainj01UjtfVXRDtcjV9vbh5pYYjZsX8lLZAdW8OZeKxhaOv7zQyUtAwMHE/sGfKj1yQSDh2fscY48mepV7xUPVE7jRgUDk1ayt2a+WeGE2DCR3KBv5gkk=
  matrix:
  - WITH_REGRESSION=true
  - TEST_MONKEYPATCHES=true WITH_REGRESSION=true
  - RUST_BACKTRACE=1 ENCODING=true TEST_MONKEYPATCHES=true WITH_REGRESSION=true
matrix:
  allow_failures:
  - env: RUST_BACKTRACE=1 ENCODING=true TEST_MONKEYPATCHES=true WITH_REGRESSION=true
  - os: linux
    rvm: 2.5.0
    env: LONG_RUN=20
    script: bundle exec rake pbench
  - os: linux
    rvm: 2.3.5
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.3.6
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.4.2
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.4.3
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.5.0
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.3.5
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.3.6
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.4.2
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.4.3
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.5.0
    if: tag =~ ^v0
    env:
  include:
  - os: linux
    rvm: 2.5.0
    env: LONG_RUN=20
    script: bundle exec rake pbench
  - os: linux
    rvm: 2.3.5
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.3.6
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.4.2
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.4.3
    if: tag =~ ^v0
    env:
  - os: linux
    rvm: 2.5.0
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.3.5
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.3.6
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.4.2
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.4.3
    if: tag =~ ^v0
    env:
  - os: osx
    rvm: 2.5.0
    if: tag =~ ^v0
    env:
before_install:
- curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
- gem install bundler
deploy:
  provider: releases
  api_key:
    secure: NhCKpRLm/aOLOoFuoXHkc1AgNIoIRlVrZs08VxJ7Hbjw0/iUX4Uq+0DloX9NVRKupd3oVH/p6gNnPQEkOdpDmx+4x8KdlwX3uYLOQ8LZTjjarOb+3StDsl748Zm1dnO69SkVHZPQ6m6W2ITg065eH82pF83QUp6Th7MLuF8f9F4Dlgdt4thHtqU43VWWRGQAT0/haLZhdKczCQJDuWrDbPHNCZwgCdm59htSmQHL1FyWAehymGy+iI9fKvs+ZifRqV/PxvC3nJSEKFbFW/aq/1LvA0AL2GKjClODiklDGdMoDsFFH6t889ZYMgIzOITP7O3cpN2+Y5tMy03U8Yf4hKg8M0fPoA1ufJ2k+OGNEFOcLeWfbwZrdLEBsm+U8vZ/r2pvz4837IA/vrHbFUFnT8ynv+JZfyaNwKNh7durRgOJYHpwsxqe/PSjlQocL1Z0FBeMVKQYViIz4g/rgBzQHwyrzou6FSGhk3kYRMD2+gPuZ+pj/hnWXc/fF3UvtAcFOxuQrk07OA7T9sZhHhA+/lQCYhVNA1YQen01dkX1yYmA+jpZvZ3p6gyhmvHksEmrJIu912QPMWFehtjPlF4te7FppQYDdjBpyePIZs0GLz6Puf5YjVu6E2knfHQzTIM3nvSko17D9fDv7d/1oXuMgiOlM0YzRPeEtr6TtGwee98=
  file: faster_path-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: -z ${TEST_MONKEYPATCHES}
    repo: danielpclark/faster_path
    tags: true
after_success: bundle exec rake thermite:tarball
