[package]
name = "faster_path"
version = "0.0.1"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
description = "Alternative to Pathname"
homepage = "https://github.com/danielpclark/faster_path"
repository = "https://github.com/danielpclark/faster_path"
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
name = "faster_path"
crate-type = ["dylib"]

[dependencies]
ruru = "0.9.3"
array_tool = "0.4.1"
lazy_static = "1.0"
memchr = "2.0.1"
